# Generated by Django 4.1 on 2023-05-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000, unique=True, verbose_name='URL')),
                ('title', models.CharField(max_length=2000, verbose_name='Заголовок')),
                ('abstract', models.TextField(verbose_name='Анотація')),
                ('content', models.TextField(verbose_name='Вміст')),
            ],
            options={
                'verbose_name': 'Веб-ресурс',
                'verbose_name_plural': 'Веб-ресурси',
            },
        ),
    ]
